ALTER TABLE users
  ADD COLUMN IF NOT EXISTS ai_tier TEXT NOT NULL DEFAULT 'free';

UPDATE users
SET ai_tier = 'pro'
WHERE is_pro = TRUE
  AND ai_tier = 'free';

ALTER TABLE users
  ADD CONSTRAINT users_ai_tier_check
  CHECK (ai_tier IN ('free', 'basic', 'plus', 'pro')) NOT VALID;

ALTER TABLE users VALIDATE CONSTRAINT users_ai_tier_check;

CREATE TABLE IF NOT EXISTS usage_counters (
  user_id TEXT NOT NULL,
  period_start TIMESTAMPTZ NOT NULL,
  period_end TIMESTAMPTZ NOT NULL,
  interactions_used INTEGER NOT NULL DEFAULT 0,
  tier TEXT NOT NULL DEFAULT 'free',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, period_start),
  CHECK (interactions_used >= 0),
  CHECK (tier IN ('free', 'basic', 'plus', 'pro')),
  CHECK (period_end > period_start)
);

CREATE INDEX IF NOT EXISTS idx_usage_counters_period
  ON usage_counters(period_start, period_end);

CREATE TABLE IF NOT EXISTS ip_rate_limit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ip_rate_limit_events_hash_created
  ON ip_rate_limit_events(ip_hash, created_at DESC);

ALTER TABLE usage_counters DISABLE ROW LEVEL SECURITY;
ALTER TABLE ip_rate_limit_events DISABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION consume_ai_interaction(
  counter_user_id TEXT,
  counter_tier TEXT,
  counter_period_start TIMESTAMPTZ,
  counter_period_end TIMESTAMPTZ,
  tier_cap INTEGER
)
RETURNS TABLE (
  allowed BOOLEAN,
  interactions_used INTEGER,
  remaining INTEGER,
  tier TEXT,
  period_start TIMESTAMPTZ,
  period_end TIMESTAMPTZ
)
LANGUAGE plpgsql
AS $$
DECLARE
  updated_row usage_counters%ROWTYPE;
  current_row usage_counters%ROWTYPE;
BEGIN
  INSERT INTO usage_counters (
    user_id,
    period_start,
    period_end,
    interactions_used,
    tier,
    updated_at
  )
  VALUES (
    counter_user_id,
    counter_period_start,
    counter_period_end,
    0,
    counter_tier,
    NOW()
  )
  ON CONFLICT (user_id, period_start) DO NOTHING;

  UPDATE usage_counters
  SET
    interactions_used = interactions_used + 1,
    tier = counter_tier,
    period_end = counter_period_end,
    updated_at = NOW()
  WHERE user_id = counter_user_id
    AND period_start = counter_period_start
    AND interactions_used < tier_cap
  RETURNING * INTO updated_row;

  IF FOUND THEN
    RETURN QUERY SELECT
      TRUE,
      updated_row.interactions_used,
      GREATEST(tier_cap - updated_row.interactions_used, 0),
      updated_row.tier,
      updated_row.period_start,
      updated_row.period_end;
    RETURN;
  END IF;

  SELECT *
  INTO current_row
  FROM usage_counters
  WHERE user_id = counter_user_id
    AND period_start = counter_period_start;

  RETURN QUERY SELECT
    FALSE,
    COALESCE(current_row.interactions_used, tier_cap),
    0,
    COALESCE(current_row.tier, counter_tier),
    COALESCE(current_row.period_start, counter_period_start),
    COALESCE(current_row.period_end, counter_period_end);
END;
$$;

CREATE OR REPLACE FUNCTION consume_ip_rate_limit(
  ip_hash TEXT,
  max_requests INTEGER,
  window_seconds INTEGER
)
RETURNS TABLE (
  allowed BOOLEAN,
  remaining INTEGER
)
LANGUAGE plpgsql
AS $$
DECLARE
  current_count INTEGER;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('ip-rate-limit:' || ip_hash));

  DELETE FROM ip_rate_limit_events
  WHERE created_at < NOW() - (window_seconds || ' seconds')::INTERVAL;

  SELECT COUNT(*)::INTEGER
  INTO current_count
  FROM ip_rate_limit_events
  WHERE ip_rate_limit_events.ip_hash = consume_ip_rate_limit.ip_hash
    AND created_at >= NOW() - (window_seconds || ' seconds')::INTERVAL;

  IF current_count >= max_requests THEN
    RETURN QUERY SELECT FALSE, 0;
    RETURN;
  END IF;

  INSERT INTO ip_rate_limit_events (ip_hash)
  VALUES (ip_hash);

  RETURN QUERY SELECT TRUE, GREATEST(max_requests - current_count - 1, 0);
END;
$$;
